app6/urls.py
from django.urls import path
from . import views

app_name = 'app6'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('add_peserta_belajar', views.add_peserta_belajar, name='add_peserta_belajar'),
    path('add_peserta_main', views.add_peserta_main, name='add_peserta_main'),
    path('add_peserta_tidur', views.add_peserta_tidur, name='add_peserta_tidur'),
    path('delete_belajar/<int:delete_id>', views.delete_belajar, name='delete_belajar'),
    path('delete_main/<int:delete_id>', views.delete_main, name='delete_main'),
    path('delete_tidur/<int:delete_id>', views.delete_tidur, name='delete_tidur'),
]

story6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app6.urls'))
]

app6/models.py
from django.db import models

class PesertaBelajar(models.Model):
    nama_peserta_belajar = models.CharField(max_length=30)

class PesertaMain(models.Model):
    nama_peserta_main = models.CharField(max_length=30)

class PesertaTidur(models.Model):
    nama_peserta_tidur = models.CharField(max_length=30)
# Create your models here.

app6/forms.py
from django import forms

class FormPesertaBelajar(forms.Form):
    nama_peserta_belajar = forms.CharField(label='Nama peserta belajar', max_length=30)

class FormPesertaMain(forms.Form):
    nama_peserta_main = forms.CharField(label='Nama peserta main', max_length=30)

class FormPesertaTidur(forms.Form):
    nama_peserta_tidur = forms.CharField(label='Nama peserta tidur', max_length=30)

app6/views.py
from django.shortcuts import render, redirect
from .models import PesertaBelajar, PesertaMain, PesertaTidur
from .forms import FormPesertaBelajar, FormPesertaMain, FormPesertaTidur

# Create your views here.
def index(request):
    response = {
        'form_peserta_belajar' : FormPesertaBelajar,
        'list_peserta_belajar' : PesertaBelajar.objects.all(),
        'form_peserta_main' : FormPesertaMain,
        'list_peserta_main' : PesertaMain.objects.all(),
        'form_peserta_tidur' : FormPesertaTidur,
        'list_peserta_tidur' : PesertaTidur.objects.all(),
    }
    return render(request, 'index.html', response)

def add_peserta_belajar(request):
    form = FormPesertaBelajar(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        add_peserta_belajar = PesertaBelajar.objects.create(nama_peserta_belajar=request.POST['nama_peserta_belajar'])
    return redirect('app6:index')

def add_peserta_main(request):
    form = FormPesertaMain(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        add_peserta_main = PesertaMain.objects.create(nama_peserta_main=request.POST['nama_peserta_main'])
    return redirect('app6:index')

def add_peserta_tidur(request):
    form = FormPesertaTidur(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        add_peserta_tidur = PesertaTidur.objects.create(nama_peserta_tidur=request.POST['nama_peserta_tidur'])
    return redirect('app6:index')

def delete_belajar(request, delete_id):
   PesertaBelajar.objects.filter(id=delete_id).delete()
   return redirect('app6:index')

def delete_main(request, delete_id):
   PesertaMain.objects.filter(id=delete_id).delete()
   return redirect('app6:index')

def delete_tidur(request, delete_id):
   PesertaTidur.objects.filter(id=delete_id).delete()
   return redirect('app6:index')

app6/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <title>Story 6 Fauzan Hanandito</title>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-sm border text-center">
                    <h1>Belajar</h1>
                    <br>
                    <div>
                        {% for s in list_peserta_belajar %}
                        <table>
                            <td> {{ s.nama_peserta_belajar }} </td>
                            <td><a href="{% url 'app6:delete_belajar' s.id %}"><button type="button">Delete</button></a></td>
                        </table>
                        {% endfor %}
                    </div>
                    <div>
                        <form action="add_peserta_belajar" method="POST">
                            {% csrf_token %}
                            {{ form_peserta_belajar.as_p }}
                            <button type="submit">Submit</button>
                        </form>
                    </div>
                </div>
                <div class="col-sm border text-center">
                    <h1>Main</h1>
                    <br>
                    <div>
                        {% for s in list_peserta_main %}
                        <table>
                            <td> {{ s.nama_peserta_main }} </td>
                            <td><a href="{% url 'app6:delete_main' s.id %}"><button type="button">Delete</button></a></td>
                        </table>
                        {% endfor %}
                    </div>
                    <div>
                        <form action="add_peserta_main" method="POST">
                            {% csrf_token %}
                            {{ form_peserta_main.as_p }}
                            <button type="submit">Submit</button>
                        </form>
                    </div>
                </div>
                <div class="col-sm border text-center">
                    <h1>Tidur</h1>
                    <br>
                    <div>
                        {% for s in list_peserta_tidur %}
                        <table>
                            <td> {{ s.nama_peserta_tidur }} </td>
                            <td><a href="{% url 'app6:delete_tidur' s.id %}"><button type="button">Delete</button></a></td>
                        </table>
                        {% endfor %}
                    </div>
                    <div>
                        <form action="add_peserta_tidur" method="POST">
                            {% csrf_token %}
                            {{ form_peserta_tidur.as_p }}
                            <button type="submit">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
          </div>
        <!-- Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>